// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/select/salon": {
    params: {};
  };
  "/select/employee": {
    params: {};
  };
  "/select/service": {
    params: {};
  };
  "/select/appointment": {
    params: {};
  };
  "/inbox": {
    params: {};
  };
  "/appointments": {
    params: {};
  };
  "/settings": {
    params: {};
  };
  "/settings/history": {
    params: {};
  };
  "/settings/privacy-policy": {
    params: {};
  };
  "/settings/faq": {
    params: {};
  };
  "/settings/profile": {
    params: {};
  };
  "/admin": {
    params: {};
  };
  "/admin/:salonId": {
    params: {
      "salonId": string;
    };
  };
  "/admin/:salonId/services-details": {
    params: {
      "salonId": string;
    };
  };
  "/admin/:salonId/employees-details": {
    params: {
      "salonId": string;
    };
  };
  "/admin/:salonId/working-hours": {
    params: {
      "salonId": string;
    };
  };
  "/admin/:salonId/archive": {
    params: {
      "salonId": string;
    };
  };
  "/*": {
    params: {
      "*": string;
    };
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/select/salon" | "/select/employee" | "/select/service" | "/select/appointment" | "/inbox" | "/appointments" | "/settings" | "/settings/history" | "/settings/privacy-policy" | "/settings/faq" | "/settings/profile" | "/admin" | "/admin/:salonId" | "/admin/:salonId/services-details" | "/admin/:salonId/employees-details" | "/admin/:salonId/working-hours" | "/admin/:salonId/archive" | "/*";
  };
  "../pages/UserDashboard.jsx": {
    id: "../pages/UserDashboard";
    page: "/";
  };
  "../pages/SelectLayout.jsx": {
    id: "../pages/SelectLayout";
    page: "/select/salon" | "/select/employee" | "/select/service" | "/select/appointment";
  };
  "../features/user/select/SelectSalon.jsx": {
    id: "../features/user/select/SelectSalon";
    page: "/select/salon";
  };
  "../features/user/select/SelectEmployee.jsx": {
    id: "../features/user/select/SelectEmployee";
    page: "/select/employee";
  };
  "../features/user/select/SelectService.jsx": {
    id: "../features/user/select/SelectService";
    page: "/select/service";
  };
  "../features/user/select/SelectAppointment.jsx": {
    id: "../features/user/select/SelectAppointment";
    page: "/select/appointment";
  };
  "../pages/UserInbox.jsx": {
    id: "../pages/UserInbox";
    page: "/inbox";
  };
  "../pages/UserAppointments.jsx": {
    id: "../pages/UserAppointments";
    page: "/appointments";
  };
  "../features/user/settings/SettingsOverview.jsx": {
    id: "../features/user/settings/SettingsOverview";
    page: "/settings";
  };
  "../features/user/settings/History.jsx": {
    id: "../features/user/settings/History";
    page: "/settings/history";
  };
  "../features/user/settings/PrivacyPolicy.jsx": {
    id: "../features/user/settings/PrivacyPolicy";
    page: "/settings/privacy-policy";
  };
  "../features/user/settings/Faq.jsx": {
    id: "../features/user/settings/Faq";
    page: "/settings/faq";
  };
  "../features/user/settings/Profile.jsx": {
    id: "../features/user/settings/Profile";
    page: "/settings/profile";
  };
  "../pages/AdminSelectSalon.jsx": {
    id: "../pages/AdminSelectSalon";
    page: "/admin";
  };
  "../pages/AdminDasboard.jsx": {
    id: "../pages/AdminDasboard";
    page: "/admin/:salonId";
  };
  "../pages/ServiceDetails.jsx": {
    id: "../pages/ServiceDetails";
    page: "/admin/:salonId/services-details";
  };
  "../pages/EmployeeDetails.jsx": {
    id: "../pages/EmployeeDetails";
    page: "/admin/:salonId/employees-details";
  };
  "../pages/WorkingHours.jsx": {
    id: "../pages/WorkingHours";
    page: "/admin/:salonId/working-hours";
  };
  "../pages/Archive.jsx": {
    id: "../pages/Archive";
    page: "/admin/:salonId/archive";
  };
  "../components/NotFound.jsx": {
    id: "../components/NotFound";
    page: "/*";
  };
};

type RouteModules = {
  "root": typeof import("./src/app/root.tsx");
  "../pages/UserDashboard": unknown;
  "../pages/SelectLayout": unknown;
  "../features/user/select/SelectSalon": unknown;
  "../features/user/select/SelectEmployee": unknown;
  "../features/user/select/SelectService": unknown;
  "../features/user/select/SelectAppointment": unknown;
  "../pages/UserInbox": unknown;
  "../pages/UserAppointments": unknown;
  "../features/user/settings/SettingsOverview": unknown;
  "../features/user/settings/History": unknown;
  "../features/user/settings/PrivacyPolicy": unknown;
  "../features/user/settings/Faq": unknown;
  "../features/user/settings/Profile": unknown;
  "../pages/AdminSelectSalon": unknown;
  "../pages/AdminDasboard": unknown;
  "../pages/ServiceDetails": unknown;
  "../pages/EmployeeDetails": unknown;
  "../pages/WorkingHours": unknown;
  "../pages/Archive": unknown;
  "../components/NotFound": unknown;
};