export const employees = [
  {
    id: 1,
    name: "Marko Marković",
    title: "Glavni berber",
    email: "marko@salon.com",
    phone: "065 123 456",
    services: [1],
  },
  {
    id: 2,
    name: "Ana Anić",
    title: "Frizerka",
    email: "ana@salon.com",
    phone: "066 987 654",
    services: [1, 2],
  },
  {
    id: 3,
    name: "Igor Igorovic",
    title: "Frizer",
    email: "igor@salon.com",
    phone: "066 333 444",
    services: [1, 2],
  },
];
// export const rasporedPoRadnicima = [[{}], [{}], [{}]];
export const rasporedPoRadnicima = [
  // Niz za Radnika 1 (npr. Marko)
  [
    {
      id: 201,
      employee: "Marko",
      employeeId: "1",
      start: "08:00",
      end: "09:30",
      client: "Nikola J.",
      service: "Šišanje",
      status: "odrađeno",
    },
    {
      id: 202,
      employee: "Marko",
      employeeId: "1",
      start: "08:30",
      end: "20:00",
      client: "Denis K.",
      service: "Brijanje",
      status: "odrađeno",
    },
  ],

  // Niz za Radnika 2 (npr. Ana)
  [
    {
      id: 301,
      employee: "Ana",
      employeeId: "2",
      start: "09:00",
      end: "08:45",
      client: "Sara M.",
      service: "Feniranje",
      status: "odrađeno",
    },
  ],

  // Niz za Radnika 3 (npr. Igor)
  [
    {
      id: 401,
      employee: "Igor",
      employeeId: "3",
      start: "08:00",
      end: "09:00",
      client: "Marko V.",
      service: "Farbanje",
      status: "potvrđeno",
    },
    {
      id: 402,
      employee: "Igor",
      employeeId: "3",
      start: "09:00",
      end: "10:00",
      client: "Marko V.",
      service: "Farbanje",
      status: "potvrđeno",
    },
    {
      id: 403,
      employee: "Igor",
      employeeId: "3",
      start: "10:00",
      end: "17:30",
      client: "Marko V.",
      service: "Farbanje",
      status: "potvrđeno",
    },
    {
      id: 404,
      employee: "Igor",
      employeeId: "3",
      start: "18:00",
      end: "18:30",
      client: "Marko V.",
      service: "Farbanje",
      status: "potvrđeno",
    },
  ],
];
export const terminiZaDanas = [
  {
    id: 201,
    employee: "Marko",
    employeeId: "1",
    start: "08:00",
    end: "09:30",
    client: "Nikola J.",
    service: "Šišanje",
    status: "odrađeno",
  },
  {
    id: 202,
    employee: "Marko",
    employeeId: "1",
    start: "08:30",
    end: "09:00",
    client: "Denis K.",
    service: "Brijanje",
    status: "odrađeno",
  },
  {
    id: 2043,
    employee: "Marko",
    employeeId: "1",
    start: "08:30",
    end: "20:00",
    client: "Denis K.",
    service: "Brijanje",
    status: "odrađeno",
  },
];
export const termini = [
  {
    id: 1,
    date: "28.10.",
    start: "10:00",
    client: "Nikola N.",
    service: "Šišanje",
    employee: "Marko",
    status: "Odradjeno",
    price: "15 KM",
  },
  {
    id: 2,
    date: "27.10.",
    start: "14:30",
    client: "Dino D.",
    service: "Brijanje",
    employee: "Ana",
    status: "No show",
    price: "10 KM",
  },
];
export const stariTermini = [
  {
    employeeId: 1,
    serviceId: 1,
    startTime: "12:20",
    endTime: "12:40",
    status: "ended",
  },
  {
    employeeId: 1,
    serviceId: 1,
    startTime: "12:20",
    endTime: "12:40",
    status: "ended",
  },
  {
    employeeId: 1,
    serviceId: 1,
    startTime: "12:20",
    endTime: "12:40",
    status: "ended",
  },
  {
    employeeId: 1,
    serviceId: 1,
    startTime: "12:20",
    endTime: "12:40",
    status: "ended",
  },
  {
    employeeId: 1,
    serviceId: 1,
    startTime: "12:20",
    endTime: "12:40",
    status: "ended",
  },
  {
    employeeId: 1,
    serviceId: 1,
    startTime: "12:20",
    endTime: "12:40",
    status: "ended",
  },
  {
    employeeId: 1,
    serviceId: 1,
    startTime: "12:20",
    endTime: "12:40",
    status: "ended",
  },
];
export const mockTermini = [
  {
    employeeId: 1,
    serviceId: 1,
    startTime: "12:20",
    endTime: "12:40",
    status: "confirmed",
  },
  {
    employeeId: 1,
    serviceId: 1,
    startTime: "12:20",
    endTime: "12:40",
    status: "confirmed",
  },
  {
    employeeId: 1,
    serviceId: 1,
    startTime: "12:20",
    endTime: "12:40",
    status: "confirmed",
  },
  {
    employeeId: 1,
    serviceId: 1,
    startTime: "12:20",
    endTime: "12:40",
    status: "confirmed",
  },
];
